#ifndef NEWTYPE_H
#define NEWTYPE_H

#include <SDL2/SDL.h>
#include <cstdint>
#include "Macros.h"
#include <string.h>

typedef enum MUSIC_TRACKS {
	MUSIC_BACKGROUND,
	MUSIC_BACKGROUND_LOWCOST,
	MUSIC_BUMBLEBEE,
	MUSIC_BUMBLEBEE_RUN,
	MUSIC_BUMBLEBEE_EXPLOSION,
	MUSIC_BUMBLEBEE_TRANSFORM,
	MUSIC_BUTTON_CLICKED,
	MUSIC_CRASH,
	MUSIC_GAMEOVER,
	MUSIC_GET_BOX,
	MUSIC_MAX
} MUSIC_TRACK;

typedef enum TEXTURES {
	TEXTURE_NUMBER_0,
	TEXTURE_NUMBER_1,
	TEXTURE_NUMBER_2,
	TEXTURE_NUMBER_3,
	TEXTURE_NUMBER_4,
	TEXTURE_NUMBER_5,
	TEXTURE_NUMBER_6,
	TEXTURE_NUMBER_7,
	TEXTURE_NUMBER_8,
	TEXTURE_NUMBER_9,
	TEXTURE_SCREEN,
	TEXTURE_HIGH_SCORE_FIELD,
	TEXTURE_PLAYER_CAR,
	TEXTURE_PLAYER_CAR_FLY,
	TEXTURE_PLAYER_CAR_FLY_UP,
	TEXTURE_PLAYER_CAR_FLY_DOWN,
	TEXTURE_PLAYER_CAR_CRASH,
	TEXTURE_PLAYER_CAR_RUN,
	TEXTURE_PLAYER_CAR_TRANSFORM,
	TEXTURE_LOGO,
	TEXTURE_STATUS_SCORE,
	TEXTURE_STATUS_LEVEL,
	TEXTURE_STATUS_FLY,
	TEXTURE_OPPOSITE_CAR_0,
	TEXTURE_OPPOSITE_CAR_1,
	TEXTURE_OPPOSITE_CAR_2,
	TEXTURE_OPPOSITE_CAR_3,
	TEXTURE_OPPOSITE_CAR_4,
	TEXTURE_OPPOSITE_CAR_5,
	TEXTURE_OPPOSITE_CAR_6,
	TEXTURE_GAME_BACKGROUND,
	TEXTURE_GAMEOVER_BACKGROUND,
	TEXTURE_GAMEOVER_CRASH,
	TEXTURE_GAME_INTRO,
	TEXTURE_GAME_MENU,
	TEXTURE_GAME_INFOR,
	TEXTURE_GAME_LEADERBOARD,
	TEXTURE_BUTTON_LEADERBOARD,
	TEXTURE_BUTTON_PLAY,
	TEXTURE_BUTTON_QUIT,
	TEXTURE_BUTTON_BACK,
	TEXTURE_BUTTON_PAUSE,
	TEXTURE_BUTTON_PAUSE_OPTIONS,
	TEXTURE_BUTTON_RESTART,
	TEXTURE_BUTTON_RESUME,
	TEXTURE_BUTTON_SOUND_OFF,
	TEXTURE_BUTTON_SOUND_ON,
	TEXTURE_BUTTON_SOUND_OFF_1,
	TEXTURE_BUTTON_SOUND_ON_1,
	TEXTURE_BUTTON_HOME,
	TEXTURE_BUTTON_INFOR,
	TEXTURE_SPECIAL_BOX,
	TEXTURE_SCROLL_BAR,
	TEXTURE_STOP_WATCH,
	TEXTURE_EXPLOSIVE_EFFECT,
	TEXTURE_MAX
} TEXTURE;

struct F1GP_CAR{
	int pos_x;
	int pos_y;
	int dx;
	int dy;
	TEXTURE image;
	TEXTURE image_fly;
	TEXTURE image_run;
	TEXTURE image_transform;
};

struct F1GP_OPPOSITE_CAR_TYPE{
	int dx;
	int dy;
	int speed;
	int dx_from_road;
	TEXTURE image;
};

struct F1GP_OPPOSITE_CAR{
	int dx;
	int dy;
	int speed;
	int dx_from_road;
	TEXTURE image;
	int pos_x;
	int pos_y;
	int road_id;
	bool is_empty;
	bool is_add_score;
	bool is_special_box;
};

#endif
